### PR TITLE
nats: Add Seabios testing

### PR DESCRIPTION
**Pull request by rbradford**
Add testing of Seabios with CentOS and (direct kernel) Clear Linux. Address a segfault from #183.

### CODE REVIEW

**Review by sameo — APPROVED** [review]

**Comment by fangying** [comment]
I was told that NEMU has seabios support with the virt machine type now, is there any doc about how to use seabios with NEMU ? @rbradford 


https://github.com/rbradford/seabios/tree/virt-x86

**Comment by rbradford** [comment]
@fangying Seabios is very straightforward to build and run with NEMU. You can recreate the steps in the script: https://github.com/intel/nemu/pull/189/files#diff-37332fbd989f3d5b31b2ac51bc31b1e7R93

**Comment by fangying** [comment]
@rbradford To test NEMU with seabios as the bootloader, I built a seabios bin following your guide but I could not luanch the VM. Could you give me some insight here ?

The VM was installed using cmd 
```
/root/nemu/build-x86_64/x86_64-softmmu/qemu-system-x86_64 \
            -machine q35,accel=kvm,kernel_irqchip \
            -cpu host -m 4096,slots=4,maxmem=16950M \
            -smp 2 \
            -device virtio-blk-pci,drive=image \
            -drive if=none,id=image,file=./diskvm-bios.img \
            -device virtio-serial-pci,id=virtio-serial0 \
            -device virtconsole,chardev=charconsole0,id=console0 \
            -chardev stdio,id=charconsole0 \
            -device virtio-blk-pci,drive=iso \
            -drive if=none,id=iso,file=./CentOS-7-x86_64-Minimal-1804.iso \
            -vnc :0
```
and I try to launch VM with cmd
```
/root/nemu/build-x86_64_virt/x86_64_virt-softmmu/qemu-system-x86_64_virt \
        -bios seabios/out/bios.bin \
        -machine virt,accel=kvm,kernel_irqchip \
        -cpu host \
        -m 4096,slots=4,maxmem=16950M \
        -smp 4 \
        -device virtio-serial-pci,id=virtio-serial0 \
        -device virtconsole,chardev=charconsole0,id=console0 \
        -chardev stdio,id=charconsole0 \
        -device sysbus-debugcon,iobase=0x402,chardev=debugcon \
        -chardev file,path=/tmp/debug-log,id=debugcon \
        -device sysbus-debugcon,iobase=0x3f8,chardev=serialcon \
        -chardev file,path=/tmp/serial-log,id=serialcon \
        -device virtio-blk-pci,drive=disk -drive if=none,id=disk,file=diskvm-bios.img \
        -netdev user,id=mynet0,hostfwd=tcp::2222-:22,hostname=nemuvm \
        -device virtio-net-pci,netdev=mynet0
```

**Comment by rbradford** [comment]
@fangying Check the serial and debug output files.

**Comment by fangying** [comment]
@rbradford Debug output file shows seabios is booted successfully and serial output file shows nothing. 
I see some error msg printed by NEMU, I think there may be something wrong with virtio during guest kernel boot . Really odd.
```
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x0 value 0xfcf3
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x13 value 0xf0
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x3 value 0xac
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xc value 0xfc86
𤬵-system-x86_64_virt: virtio_ioport_write: unexpected address 0x9 value 0x2b
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xa value 0x1d
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x9 value 0x3
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xa value 0x83
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x0 value 0x8300
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xc value 0xd2c1
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xb value 0x9d
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xc value 0xdd
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xc value 0x1a4
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x13 value 0x4
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xf value 0x6b
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x2 value 0x8357
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x7 value 0xf6
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x5 value 0x96
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x6 value 0xfb
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xa value 0xfc33
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x5 value 0xa8
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x6 value 0xd5
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0x9 value 0xa5
qemu-system-x86_64_virt: virtio_ioport_write: unexpected address 0xa value 0xfb
qemu-system-x86_64_virt: virtio: zero sized buffers are not allowed
```

**Comment by yangzhon** [comment]
@rbradford 

I reproduced this issue with latest nemu and seabios code, the seabios binary used virt_x86.config file to build.  thanks!

My nemu command: 
sudo /home/chen/build-x86_64_virt/x86_64_virt-softmmu/qemu-system-x86_64_virt \
     -bios /home/chen/project/nemu-seabios/seabios/out/bios.bin \
     -nographic \
     -nodefaults \
     -L . \
     -machine virt,accel=kvm,kernel_irqchip \
     -smp sockets=1,cpus=4,cores=2,maxcpus=8 -cpu host \
     -m 512 \
     -device sysbus-debugcon,iobase=0x402,chardev=debugcon -chardev file,path=/tmp/debug-log,id=debugcon \
     -device virtio-blk-pci,drive=image -drive if=none,id=image,file=/home/chen/Downloads/clear-24380-cloud.img \
     -device virtio-serial-pci,id=virtio-serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev stdio,id=charconsole0 \
     -monitor telnet:127.0.0.1:55555,server,nowait

**Comment by rbradford** [comment]
@yangzhon @fangying  It's no longer necessary to use workaround install method. I've updated [the wiki](https://github.com/intel/nemu/wiki/Running-NEMU#fedora-cloud-basecentos-genericcloudrhel-guest) to explain that it is supported.

I was not able to reproduce your issue with the instructions documented there.

**Comment by rbradford** [comment]
@yangzhon I think your NEMU is old as your "-smp" line fails the newer validation code. Also Clear Linux does not support legacy BIOS so will never boot with Seabios except in direct boot mode (e.g. with a -kernel line)

**Comment by fangying** [comment]
Thanks. I am able to boot the kernel with seabios now. My new cmdline is 
```
/root/nemu/build-x86_64_virt/x86_64_virt-softmmu/qemu-system-x86_64_virt \
-bios seabios/out/bios.bin \
-nographic \
-nodefaults \
-L . \
-net none \
-machine virt,accel=kvm,kernel_irqchip \
-cpu host \
-m 512,slots=4,maxmem=16950M \
-smp 4 \
-device sysbus-debugcon,iobase=0x402,chardev=debugcon \
-chardev file,path=/tmp/debug-log,id=debugcon \
-device sysbus-debugcon,iobase=0x3f8,chardev=serialcon \
-chardev file,path=/tmp/serial-log,id=serialcon \
-device virtio-blk-pci,drive=image \
-drive if=none,id=image,file=./diskvm-bios.img \
-device virtio-serial-pci,id=virtio-serial0 \
-device virtconsole,chardev=charconsole0,id=console0 \
-chardev stdio,id=charconsole0 \
-netdev user,id=mynet0,hostfwd=tcp::2222-:22,hostname=nemuvm \
-device virtio-net-pci,netdev=mynet0
```
 What's more, I find that when seabios is used as the bootloader for virt type machine, NEMU must fail to boot guset kernel with the memory configured btw 2048m and 4096 m here. It is quite odd. I will figure it out later.

**Pull request merged**
