### PR TITLE
Fix full build issue during the hw configurable

### LINKED ISSUE #102: The hw configurable impact other platform build
@sameo @rbradford 

I am disabling APIC and IOAPIC device model since the irq will offload to kernel.  when i did full build with below command
./configurable 

There are many build errors during all platform builds, some built-in files have been configurable, we need add this CONFIG_XXX to all platforms, this is the reason why i added one hw-common.mak before. If we do not use this file, we need to add each CONFIG_XXX into each XXX-softmmu.mak file because we are not sure if each platform will need this CONFIG_XXX. thanks!

### PR DESCRIPTION
**Pull request by yangzhon**
@sameo @rbradford

Please help review this PR, and this PR can fix  #102. thanks!

How to verify FULL build issue
(1) ../configure
(2) make -j8
You will find some USB and some other build errors.

### CODE REVIEW

**Comment by rbradford** [comment]
@yangzhon i rebased your branch for you.

**Comment by yangzhon** [comment]
@rbradford

Many thanks!

**Comment by yangzhon** [comment]
@rbradford

Many thanks!

**Comment by yangzhon** [comment]
@rbradford 

Wow, many thanks!

**Comment by yangzhon** [comment]
> @yangzhon i rebased your branch for you.

@rbradford , many thanks!

**Review by sameo — COMMENTED** [review]
All 4 patches look good to me, but could you please fix the commit message to follow a more idiomatic subject format: `subsystem: commit subject`?
So the USB build issue would be:
```
default-configs: Fix USB redirection build failure
```

**Comment by yangzhon** [comment]
@sameo @rbradford 

Addressed samuel's comments, please review again, thanks!

**Review by sameo — APPROVED** [review]
LGTM

**Pull request merged**
