### PR TITLE
build: Change releasing mechanism

### PR DESCRIPTION
**Pull request by rbradford**
A draft release will be created now from any tag including uploading any
binary artifacts. This release can then be "undrafted" to expose it to
the public.

This allows making releases with any names from any branch.

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@sboeuf can you grab this onto your PR (cherry-pick -x) and then see if you can get a release out from a tag on your branch.

**Comment by sboeuf** [comment]
@rbradford yes will do!

**Comment by sboeuf** [comment]
@rbradford it worked, take a look at #217, that's where the pre-release https://github.com/intel/nemu/releases/tag/nemu-virtio-fs-1 has been generated from.

**Review by sboeuf — APPROVED** [review]
LGTM and tested in the context of NEMU + virtio-fs pre-release.

**Pull request merged**
