### PR TITLE
PIIX4: remove PC platform

### PR DESCRIPTION
**Pull request by yangzhon**
Remove all PC platform related codes, NEMU only support
Q35 platform now.

@sameo @anthonyzxu @mcastelino 
Please help me review this patch, this patch will remove PC platform support.

This patch has passed CI test

19:19 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64
[sudo] password for chen:
Testing safe images
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_q35 https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_q35 https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_q35 http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified

19:39 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -unsafe
Testing unsafe images
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_q35 https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified

### CODE REVIEW

**Review by mcastelino — CHANGES_REQUESTED** [review]
@yangzhon we should consider a different way to structure this code. Can we modify this work such that PIIX support becomes a compile time option vs completely removing the code.

The reason we want to provide a way to remove PIIX is to eliminate any accidental dependencies between PIIX and Q35, it to decouple PIIX and Q35, so that we can define a Q35-modern platform with the absolute minimum set of devices.

We will need to support PIIX for legacy when needed.

**Review by mcastelino — CHANGES_REQUESTED** [review]
@yangzhon also we need to add an option to the minimal CI to only test q35. So that the minimal CI can actually run automatically once this change is enabled.

Also we will need to test two distinct cases once this PR gets merged.

PIIX enabled, test all images

PIIX disabled, test only Q35 with modern images.

**Comment by yangzhon** [comment]
@sameo @anthonyzxu @mcastelino

Please help me review new disable patch according to @mcastelino's suggestion, i also changed the CI script for disable-piix.

Notice: I feel hw/i386/acpi-build.c is not clean after i add CONFIG_PIIX config, the code is a little mess .
Let me check if i can split this file into 3 files.

The disbale-piix or enable-piix binary can pass all images test.

20:09 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -piix
[sudo] password for chen:
Testing safe images
Testing clear-22180-cloud.img qcow2 uefi x86_64_pc https://download.clearlinux.org/releases/22180/clear/clear-22180-cloud.img.xz :
SUCCESS: SSH connectivity verified
Testing CentOS-6-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_pc https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_pc https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing bionic-server-cloudimg-amd64.img qcow2 seabios x86_64_pc http://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_pc https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_pc http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_q35 https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_q35 https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_q35 http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
20:18 chen:~$
20:22 chen:~$
20:22 chen:~$
20:22 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -piix -unsafe
Testing unsafe images
Testing ubuntu-12.04-server-cloudimg-amd64-disk1.img qcow2 seabios x86_64_pc http://cloud-images-archive.ubuntu.com/releases/precise/release-20170502/ubuntu-12.04-server-cloudimg-amd64-disk1.img :
SUCCESS: SSH connectivity verified
Testing ubuntu-11.10-server-cloudimg-amd64-disk1.img qcow2 seabios x86_64_pc http://cloud-images-archive.ubuntu.com/releases/oneiric/release-20130509/ubuntu-11.10-server-cloudimg-amd64-disk1.img :
SUCCESS: SSH connectivity verified
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_pc https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-20141203-21.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/21/Cloud/Images/x86_64/Fedora-Cloud-Base-20141203-21.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_q35 https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified
20:26 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -unsafe
Testing unsafe images
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_q35 https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified
20:27 chen:~$
20:29 chen:~$
20:29 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64
Testing safe images
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_q35 https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_q35 https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_q35 http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified

**Comment by sameo** [comment]
@yangzhon @mcastelino I think this looks good. The acpi-build.c file is unfortunately more complex now with all the added ifdefs. It would be good to split this file in 3 (core, q35 and piix) not only for the sake of getting this PR merged but also as a first step towards building a modern, purely virtual platform for x86. It would need the minimal ACPI settings and ideally would only use acpi-build-core.c.

**Comment by yangzhon** [comment]
@mcastelino @sameo 

About the remove PC platform code in the compile time, there are two solutions can be done
(1) disable-piix/enable-piix in configure 
+  --disable-piix) piix="no"
+  ;;
+  --enable-piix) piix="yes"
+  ;;
if piix=yes, which will set CONFIG_PIIX=y

(2) Directly add CONFIG_PIIX=y into default-configs/x86_64-softmmu.mak

Which solution do you prefer ?  

It seems like (1) is mostly for whole system level and (2) is for HW side

**Comment by sameo** [comment]
@yangzhon @mcastelino 
> We will need to support PIIX for legacy when needed.

One fundamental question here: Do we want to support PIIX and Q35 from the same binary when legacy is needed? Or are we ok to have a different binary for each platform? The latter makes the ACPI build code refactoring a lot cleaner.

**Comment by mcastelino** [comment]
@yangzhon @sameo when we do the platform reduction it is best to have a separate binary. It means that we will need to create a new top level file say `default-configs/x86_64-virt`. That will also allow us to move forward without breaking legacy in a cleaner manner.

**Comment by yangzhon** [comment]
@mcastelino @sameo

I re-made the patch and splited acpi-build.c file to acpi-build-core,c acpi-build-piix.c and acpi-build-q35.c files, also added extra acpi-build-stub.c file for non PIIX build in acpi-build-core.c.

Now the PIIX code have been removed during the compile, the PIIX platform default is disabled, if you want to enable PIIX, you can add --enable-piix in the config file.

I used the piix_enabled() function to make sure all PIIX code removed during the compile and objdumped the qemu system binary to check if PIIX code exist.  

Now the code can support:
(1)q35 only build
(2) piix+q35 build
If we want to pure piix build binary, i can do it next step.

By the way, i also changed the CI tool for disable-piix. All CI passed test.

(1)pure Q35
14:12 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64
Testing safe images
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_q35 https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_q35 https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_q35 http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
14:16 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -unsafe
Testing unsafe images
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_q35 https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified

(2) PIIX+Q35
14:18 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -piix
Testing safe images
Testing clear-22180-cloud.img qcow2 uefi x86_64_pc https://download.clearlinux.org/releases/22180/clear/clear-22180-cloud.img.xz :
SUCCESS: SSH connectivity verified
Testing CentOS-6-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_pc https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_pc https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing bionic-server-cloudimg-amd64.img qcow2 seabios x86_64_pc http://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_pc https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_pc http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing coreos_production_openstack_image.img qcow2 seabios x86_64_q35 https://stable.release.core-os.net/amd64-usr/current/coreos_production_openstack_image.img.bz2 :
SUCCESS: SSH connectivity verified
Testing CentOS-7-x86_64-GenericCloud-1802.qcow2 qcow2 seabios x86_64_q35 https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1802.qcow2 :
SUCCESS: SSH connectivity verified
Testing CentOS-Atomic-Host-7-GenericCloud.qcow2 qcow2 seabios x86_64_q35 http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-GenericCloud.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-AtomicHost-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/AtomicHost/x86_64/images/Fedora-AtomicHost-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-27-1.6.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-28-1.1.x86_64.qcow2 qcow2 seabios x86_64_q35 https://archives.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2 :
SUCCESS: SSH connectivity verified

14:32 chen:~$ sudo -E ~/nemu/tools/CI/minimal_ci.sh -hypervisor ~/build-x86_64/x86_64-softmmu/qemu-system-x86_64 -piix -unsafe
Testing unsafe images
Testing ubuntu-12.04-server-cloudimg-amd64-disk1.img qcow2 seabios x86_64_pc http://cloud-images-archive.ubuntu.com/releases/precise/release-20170502/ubuntu-12.04-server-cloudimg-amd64-disk1.img :
SUCCESS: SSH connectivity verified
Testing ubuntu-11.10-server-cloudimg-amd64-disk1.img qcow2 seabios x86_64_pc http://cloud-images-archive.ubuntu.com/releases/oneiric/release-20130509/ubuntu-11.10-server-cloudimg-amd64-disk1.img :
SUCCESS: SSH connectivity verified
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_pc https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified
Testing Fedora-Cloud-Base-20141203-21.x86_64.qcow2 qcow2 seabios x86_64_pc https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/21/Cloud/Images/x86_64/Fedora-Cloud-Base-20141203-21.x86_64.qcow2 :
SUCCESS: SSH connectivity verified
Testing core-stable-amd64-disk1.img qcow2 seabios x86_64_q35 https://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-disk1.img :
SUCCESS: SSH connectivity verified

**Comment by sameo** [comment]
LGTM.
I think this is the right first step. The next one will be to completely remove the `piix_enabled()` parts from `acpi-build-core.c` but this could be a follow up PR.
To me this can go in, waiting for @mcastelino's input.

**Comment by mcastelino** [comment]
LGTM I will merge this

**Review by mcastelino — APPROVED** [review]

**Comment by sameo** [comment]
I cherry picked those changes into master now.

**Pull request merged**
