### PR TITLE
i386: virt: Remove emulated IOMMUs from allowed devices

### PR DESCRIPTION
**Pull request by rbradford**
Remove the emulated IOMMUs from the list of devices that the user is
allowed to create when using the virt platform.

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
I am fine with that one as I'm not sure why we'd want to emulate an IOMMU from virt. But I may be missing some use cases and I'd like to get @mcastelino input.

**Comment by rbradford** [comment]
And further, they don't work as they assume PC machines.

**Comment by sameo** [comment]
> And further, they don't work as they assume PC machines.

Correct. From `hw/i386/x86-iommu.c` for example:

```C
static void x86_iommu_realize(DeviceState *dev, Error **errp)
{
    X86IOMMUState *x86_iommu = X86_IOMMU_DEVICE(dev);
    X86IOMMUClass *x86_class = X86_IOMMU_GET_CLASS(dev);
    MachineState *ms = MACHINE(qdev_get_machine());
    MachineClass *mc = MACHINE_GET_CLASS(ms);
    PCMachineState *pcms =
        PC_MACHINE(object_dynamic_cast(OBJECT(ms), TYPE_PC_MACHINE));
    QLIST_INIT(&x86_iommu->iec_notifiers);

    if (!pcms || !pcms->bus) {
        error_setg(errp, "Machine-type '%s' not supported by IOMMU",
                   mc->name);
        return;
    }
[...]
}
```

That being said, I think the x86 IOMMU drivers for QEMU are wrongly designed. It currently depends on PC machines because it needs a PCI bus, there are no PC machine type specific dependency per se. 
However, the `x86_iommu` type's parent is the system bus whereas having it being a PCI bus child would make it completely PC machine independent for it to fetch a PCI bus.

So, if we decide that we still want to support IOMMU emulation, we need to fix that. Otherwise, this patch LGTM.

**Comment by sameo** [comment]
@rbradford Also, could we disable `CONFIG_VTD` and `CONFIG_AMD_IOMMU` from the virt config?

**Comment by rbradford** [comment]
> @rbradford Also, could we disable `CONFIG_VTD` and `CONFIG_AMD_IOMMU` from the virt config?

Great idea. Done!

**Review by sboeuf — APPROVED** [review]

**Review by mcastelino — APPROVED** [review]
LGTM.

If we do want to support it we will need to support at the very minimum

```
kernel_irqchip=split
```

**Comment by mcastelino** [comment]
> I am fine with that one as I'm not sure why we'd want to emulate an IOMMU from virt. But I may be missing some use cases and I'd like to get @mcastelino input.

The place where we may need it is the case of vfio. When we directly assign a device to the VM, and we want to offer VT-d protections to the guest memory.

**Review by sameo — APPROVED** [review]
LGTM

**Pull request merged**
