### PR TITLE
QEMU 4.0 rc0 rebase

### PR DESCRIPTION
**Pull request by yangzhon**
@sameo ,

Please help me review these patches, there are lots of changes between Qemu 4.0 and Qemu 3.1. Please focus on pvh, loader, acpi(RSDP) and flash related files, thanks!  

#nemu porting patch history
##. removed patch list
1)0007-target-arm-Move-all-VFP-helpers-into-their-own-file.patch
old commit id: 49b4228
reason: there is one vfp_helper.c in target/arm of QEMU4.0
(2)0046-hw-arm-Switch-to-the-AML-build-RSDP-building-routine.patch
old commit id: 1759f04
reason: build_rsdp() has been moved to aml-build.c in QEMU4.0

##. new patch added list
(1)0030: i386: virt refactor load_linux with conf struct
commit id: 764c7e5
reason: PVH support
(2)0035: i386: refactor sysfw.c for all platforms
commit id: 4e7316d
reason: change sysfw.c for all platform
(3)0036: i386: virt: add flash support in virt platform
commit id: d620641
reason: pflash support in virt platform

##heavy changed patches
(1) 0043: hw: fw-build: Add firmware build methods and state
(2) 0047: hw: acpi: Implement XSDT support for RSDP

### CODE REVIEW

**Comment by sameo** [comment]
@yangzhon 

- The sysfw stuff is missing the flash vs non-flash split. We should not need to emulate pflash devices with virt, and this is why the pc_sysfw.c split was done on the current virt-x86 branch. So that we can build sysfw together with sysfw-stub.c when PFLASH is not enabled in the build. We should follow a similar approach here.

- Patch 47 (d2f9486a2914faf651358d829d76ec85197c1f06) should be squashed into cae2283c12b07859eb4b2a04a0af18d6c7c5cc8d (Initial hw reduced implementation)

**Comment by rbradford** [comment]
@yangzhon I created the topic/virt-x86-4.0-rc0 branch for you to target with your PR. Merging into the upsteam/4.0.0-rc0 branch makes no sense. Before going further you should update your PR.

It looks like you missed out all the commits relating to the CI.

**Comment by yangzhon** [comment]
@rbradford ,

Since there are lots of changes between Qemu4.0 and Nemu3.1, especially on loader, pc_sysfw and ACPI RSDP, i created this temp PR for Samuel to review.  This rebase will include 271 patches, and i did this rebase one by one according to patch number, so all of patches will be included into new rebase.

I found there is one new branch, topic/virt-x86-4.0-rc0-candidate, which will be rebase PR target branch?

BTW, upsteam/4.0.0-rc0 branch will be used upstream after the rebase work is over. thanks!

**Comment by rbradford** [comment]
@yangzhon If you included all the Jenkins related patches then the CI will test your commits for you. Testing is a prerequisite for review.

You must modify your PR to target the topic/virt-x86-4.0-rc0 branch. The upstream/ branches are for pristine upstream code.

You may use the topic/virt-x86-4.0-rc0-candidate to test your PR through the CI by pushing directly to that.

**Comment by sboeuf** [comment]
@yangzhon any progress on this PR? Do you have a rough estimate about when this will be done?

**Comment by yangzhon** [comment]
@sboeuf ,

I have rebased around 135 patches from NEMU3.1 to Qemu4.0 and the rebased patches get to HW/ configurable commit.

I used this commit to build and debug, now the new rebase can be worked on below:
(1)virt platform 
•	Clear image
•	“-kernel” + bzImage
•	OVMF-0.6.fd
(2)Old platforms
•	440fx
•	Q35

I will squash and make up those patches and send normal PR for the first stage.

Then, i will redo Kconfig for virt minimal CONFIGs.

In coming days, i will join in KVM workshop arranged by Nakajima ,Jun and will resume this work.

Anyway, i hope this rebase will be close quickly and will keep all posted.  thanks!

**Comment by sboeuf** [comment]
Thanks for the update @yangzhon

**Comment by sboeuf** [comment]
@yangzhon 
Hi, what's the status so far? Why is the CI not passing, is this expected?
Do you have a rough idea when this will be ready?

**Comment by rbradford** [comment]
Replaced by #213

**Pull request closed without merging**
