### PR TITLE
nats: Add support for controlling the boot process

### PR DESCRIPTION
**Pull request by rbradford**
To the distro struct, add a slice of bootConfigs which can be used to
control the boot including BIOS path and optionally kernel path and
kernel command line.

The contents of this struct is then used when constructing the QEMU
command line.

Further add support for direct kernel boot when using Clear Linux.

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

**Comment by rbradford** [comment]
@sboeuf  thank you for looking at #162! However i've refactored things slightly in this version and I think it's a bit better. WDYT?

**Comment by rbradford** [comment]
Build time increases from 23 minutes to 28 minutes. Seems reasonable to me?

**Review by sboeuf — APPROVED** [review]
@rbradford the refactoring looks fine to me!

About the time it takes to run the whole CI, 5 minutes is a pretty big bump, even if it's obviously worth it.
Could we change Jenkins so that we try to parallelize as much as possible, by using parallel jobs?

**Comment by rbradford** [comment]
@sboeuf I opened #164 to look into this

**Pull request merged**
